<?xml version="1.0"?>
<robot name="agv" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- Constants for robot dimensions -->
    <xacro:property name="PI" value="3.1415926535897931"/>
    <xacro:property name="chassis_x" value="1.5" /> <!-- length=1.5 meters -->
    <xacro:property name="chassis_y" value="1.2" /> <!-- width=1.2 meters -->
    <xacro:property name="chassis_z" value="1.5" /> <!-- height=1.5 meters-->

    <xacro:property name="mast_x" value="0.3" /> <!-- length=0.3 meters -->
    <xacro:property name="mast_z" value="3.0" /> <!-- height=3.0 meters-->

    <xacro:property name="fork_x" value="1.5" /> <!-- length=1.5 meters-->
    <xacro:property name="fork_y" value="0.2" /> <!-- width=0.2 meters-->
    <xacro:property name="fork_z" value="0.05" /> <!-- height=0.05 meters-->
    <xacro:property name="fork_y_offset" value="0.15" /> <!-- offset from center=0.15 meters-->

    <xacro:property name="wheel_rad" value="0.15" /> <!-- radius=0.15 meters-->
    <xacro:property name="wheel_len" value="0.30" /> <!-- length=0.30 meters-->

    <!-- Include other xacro files-->
    <xacro:include filename="$(find factorybot_description)/urdf/materials.xacro" />
    <xacro:include filename="$(find factorybot_description)/urdf/agv.gazebo.xarco" />

    <!-- Setup some useful xacro macros-->
    <xacro:macro name="visual_collision_template" params="x y z material *shape">
        <visual>
        <origin xyz="${x} ${y} ${z}" rpy="0 0 0"/>
        <geometry>
            <xacro:insert_block name="shape" />
        </geometry>
        <material name="${material}"/>
        </visual>

        <collision>
        <origin xyz="${x} ${y} ${z}" rpy="0 0 0"/>
        <geometry>
            <xacro:insert_block name="shape" />
        </geometry>
        </collision>
    </xacro:macro>
    <xacro:macro name="wheel_template" params="name x y rad len">
        <joint name="chassis_${name}_joint" type="continuous">
            <parent link="chassis"/>
            <child link="${name}"/>
            <origin xyz="${x} ${y} 0.0" rpy="${-PI/2} 0 0"/>
            <axis xyz="0 0 1"/>
        </joint>

        <link name="${name}">
            <xacro:visual_collision_template x="0.0" y="0.0" z="0.0" material="black">
                <cylinder radius="${rad}" length="${len}" />
            </xacro:visual_collision_template>

            <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="1"/>
            <inertia ixx="0.0145833" ixy="0" ixz="0"
                    iyy="0.0145833" iyz="0"
                    izz="0.0125" />
            </inertial>
        </link>
    </xacro:macro>


    <!-- AGV Description Starts -->
    <link name="agv_CoordSys"/>
    <joint name="base_chassis_joint" type="fixed">
        <parent link="agv_CoordSys"/>
        <child link="chassis"/>
        <origin xyz="0.0 0.0 ${wheel_rad}" rpy="0 0 0"/>
    </joint>

    <!-- AGV Chassis -->
    <link name="chassis">
        <!-- Box representing AGV body which contains battery, electronics, etc. -->
        <xacro:visual_collision_template x="0.0" y="0.0" z="${mast_z/2}" material="grey">
            <box size="${mast_x} ${chassis_y} ${mast_z}"/>
        </xacro:visual_collision_template>

        <!-- Box representing AGV mast -->
        <xacro:visual_collision_template x="${(mast_x+chassis_x)/2}" y="0.0" z="${chassis_z/2}" material="orange">
            <box size="${chassis_x} ${chassis_y} ${chassis_z}"/>
        </xacro:visual_collision_template>

        <!-- Box representing AGV forks -->
        <xacro:visual_collision_template x="${-(mast_x+fork_x)/2}" y="${fork_y_offset+fork_y/2}" z="${fork_z/2}" material="black">
            <box size="${fork_x} ${fork_y} ${fork_z}"/>
        </xacro:visual_collision_template>
        <xacro:visual_collision_template x="${-(mast_x+fork_x)/2}" y="${-(fork_y_offset+fork_y/2)}" z="${fork_z/2}" material="black">
            <box size="${fork_x} ${fork_y} ${fork_z}"/>
        </xacro:visual_collision_template>
        
        <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="100"/>
        <inertia ixx="60" ixy="0" ixz="0"
                iyy="60" iyz="0"
                izz="60" />
        </inertial>
    </link>

    <!-- AGV Wheels -->
    <xacro:wheel_template name="wheelL" x="0" y="${(chassis_y-wheel_len)/2+.01}" rad="${wheel_rad}" len="${wheel_len}"/>
    <xacro:wheel_template name="wheelR" x="0" y="${-(chassis_y-wheel_len)/2-.01}" rad="${wheel_rad}" len="${wheel_len}"/>
    <xacro:wheel_template name="wheelC" x="${chassis_x}" y="0" rad="${wheel_rad}" len="${wheel_len}"/>

    <!-- AGV Lidar3D Sensor -->
    <joint name="chassis_lidar3D_joint" type="fixed">
        <parent link="chassis"/>
        <child link="lidar3D"/>
        <origin xyz="0.0 0.0 ${mast_z+.1}" rpy="0 0 0"/>
    </joint>
    <link name="lidar3D">
        <xacro:visual_collision_template x="0.0" y="0.0" z="0.0" material="green">
            <cylinder radius="0.1" length="0.2" />
        </xacro:visual_collision_template>
    </link>

    <!-- AGV Lidar2D Sensor -->
    <joint name="chassis_lidar2D_joint" type="fixed">
        <parent link="chassis"/>
        <child link="lidar2D"/>
        <origin xyz="0.0 0.0 ${mast_z+.3}" rpy="0 0 0"/>
    </joint>
    <link name="lidar2D">
        <xacro:visual_collision_template x="0.0" y="0.0" z="0.0" material="red">
            <cylinder radius="0.1" length="0.2" />
        </xacro:visual_collision_template>
    </link>

</robot>
